apiVersion: core.openstack.org/v1beta1
kind: OpenStackVersion
metadata:
  name: openstack
spec:
  customContainerImages:
    cinderVolumeImages:
      # This image exists and was built using the Dockerfile available in the parent directory
      pure-fc: quay.io/geguileo/podified-antelope-openstack-cinder-volume-pure:current-podified
